runtime: nodejs18

env_variables:
  MOVIEREVIEWS_DB_URI: "mongodb+srv://atlas_db_user:Pass123@cluster0.4as5fop.mongodb.net/movie_time_db?retryWrites=true&w=majority"
  MOVIEREVIEWS_COLLECTION: "movie_time_db"